"""InvenioRDM REST API models.

Pydantic models representing the Zenodo/InvenioRDM record metadata schema.
These models are used to construct valid API payloads for creating and
updating Zenodo draft records.

Reference:
    https://inveniordm.docs.cern.ch/reference/metadata/

Key schema rules from the InvenioRDM spec:
  - ``relation_type`` in related_identifiers MUST be ``{"id": "<vocab_id>"}`` —
    plain strings are rejected.  Vocabulary IDs are all-lowercase, no separators
    (e.g., ``"issupplementedby"``, ``"cites"``).  See
    https://github.com/inveniosoftware/invenio-rdm-records/blob/master/
    invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
  - ``resource_type`` in related_identifiers is similarly ``{"id": "<vocab_id>"}``.
  - ``references`` entries are ``{"reference": "...", "scheme": ..., "identifier": ...}``
    objects, NOT plain strings.
  - ``scheme`` values in identifiers MUST be lowercase (e.g., ``"doi"``, ``"url"``).
  - ``given_name`` is required when ``person_or_org.type == "personal"``; use
    ``type="organizational"`` with ``name`` for anonymous or collective entities.
"""

from typing import List, Dict, Optional, Any, Literal

from pydantic import BaseModel


class Identifier(BaseModel):
    """Identifier of a person or organization.

    Attributes:
        scheme: The identifier scheme, lowercase (e.g., 'orcid', 'url', 'doi').
        identifier: Actual value of the identifier.
    """

    scheme: str
    identifier: str


class PersonOrganization(BaseModel):
    """A person or an organization.

    Attributes:
        type: Either 'personal' or 'organizational'.
        given_name: Given name(s) — required (non-empty) for personal type.
        family_name: Family name — required (non-empty) for personal type.
        name: Full name — required for organizational type.
            For personal type this is auto-generated by Zenodo from
            given_name + family_name and should be omitted.
        identifiers: Optional list of identifiers (e.g., ORCID).
    """

    type: Literal["personal", "organizational"]
    given_name: Optional[str] = None
    family_name: Optional[str] = None
    name: Optional[str] = None
    identifiers: Optional[List[Identifier]] = None


class Affiliation(BaseModel):
    """Affiliation of a person associated with a record.

    Attributes:
        id: Organizational or institutional ID from controlled vocabulary (ROR).
        name: Free-text name of the organisation or institution.

    Note:
        At least one of ``id`` or ``name`` must be present.  Use ``name``
        when no matching ROR ID is available.  Never supply an empty string
        for ``name`` — omit the affiliation entry instead.
    """

    id: Optional[str] = None
    name: Optional[str] = None


class Role(BaseModel):
    """Role of a person or organisation associated with a record.

    Attributes:
        id: Role controlled vocabulary identifier (e.g., 'datamanager',
            'datacollector', 'projectleader', 'researcher').
    """

    id: str


class Creator(BaseModel):
    """Person or organisation credited for a resource (used in citations).

    Attributes:
        person_or_org: The person or organization.
        role: The role (e.g., 'datamanager', 'projectleader').
        affiliations: Affiliations — only valid when person_or_org.type is
            'personal'.  Must not contain entries with empty names.
    """

    person_or_org: PersonOrganization
    role: Optional[Role] = None
    affiliations: Optional[List[Affiliation]] = None


class Contributor(BaseModel):
    """Person or organisation contributing to the resource (not in citations).

    Attributes:
        person_or_org: The person or organization.
        role: The role (required) — e.g., 'projectmember', 'researcher'.
        affiliations: Affiliations — only valid when person_or_org.type is
            'personal'.  Must not contain entries with empty names.
    """

    person_or_org: PersonOrganization
    role: Role
    affiliations: Optional[List[Affiliation]] = None


class ResourceType(BaseModel):
    """Type of the resource described by the record.

    Attributes:
        id: Resource type ID from controlled vocabulary (e.g., 'dataset',
            'software', 'publication-article', 'audiovisual').

    Note:
        Only ``id`` needs to be passed to the REST API.  Zenodo fills in
        the human-readable ``title`` automatically.
    """

    id: str


class License(BaseModel):
    """Rights management statement for a resource.

    Attributes:
        id: SPDX license identifier (e.g., 'cc-by-4.0').
    """

    id: str


class Language(BaseModel):
    """Language of a resource.

    Attributes:
        id: ISO-639-3 language code (e.g., 'eng').
    """

    id: str


class DateType(BaseModel):
    """Type of a date associated with a resource.

    Attributes:
        id: Date type ID from controlled vocabulary.
    """

    id: Literal[
        "accepted",
        "available",
        "collected",
        "copyrighted",
        "created",
        "issued",
        "other",
        "submitted",
        "updated",
        "valid",
        "withdrawn",
    ]


class Date(BaseModel):
    """Date relevant to a resource.

    Attributes:
        date: A date or EDTF time interval.  Use ``"YYYY-MM-DD/YYYY-MM-DD"``
            to represent a date range (e.g., recording period).
        type: The type of date (controlled vocabulary).
        description: Free text about the date.

    Example (single date):
        Date(date="2024-04-08", type=DateType(id="collected"))

    Example (date interval — preferred for recording periods):
        Date(date="2024-02-13/2024-04-08",
             type=DateType(id="collected"),
             description="Recording period")
    """

    date: str
    type: DateType
    description: Optional[str] = None


class Funder(BaseModel):
    """Funding provider.

    Attributes:
        id: Funder ROR ID from controlled vocabulary.
        name: Name of the funder (use when no matching ROR id exists).
    """

    id: Optional[str] = None
    name: Optional[str] = None


class AwardTitle(BaseModel):
    """Localized title of a funding award.

    Attributes:
        en: English title of the award.
    """

    en: str


class Award(BaseModel):
    """An award (grant) sponsored by a funder.

    Attributes:
        id: Award ID from controlled vocabulary.
        title: Localized title of the award.
        number: Grant number assigned by funder.
        identifiers: Identifiers for the award (e.g., URL).
    """

    id: Optional[str] = None
    title: Optional[AwardTitle] = None
    number: Optional[str] = None
    identifiers: Optional[List[Identifier]] = None


class Funding(BaseModel):
    """Financial support information for the resource.

    Attributes:
        funder: The funding organization.
        award: The award (grant) details.
    """

    funder: Optional[Funder] = None
    award: Optional[Award] = None


class Subject(BaseModel):
    """Subject, keyword, or classification describing the resource.

    Attributes:
        id: Identifier from controlled vocabulary.
        subject: Custom keyword string.

    Note:
        Either ``id`` or ``subject`` must be provided, not both.
    """

    id: Optional[str] = None
    subject: Optional[str] = None


class RelationType(BaseModel):
    """Relation type for a related identifier.

    InvenioRDM requires this to be a vocabulary object ``{"id": "..."}``
    rather than a plain string.

    Attributes:
        id: Relation type vocabulary ID — all lowercase, no separators.

    Common values::

        "iscitedby"        "cites"
        "issupplementto"   "issupplementedby"
        "ispartof"         "haspart"
        "isnewversionof"   "ispreviousversionof"
        "isreferencedby"   "references"
        "isdocumentedby"   "documents"
        "iscompiledby"     "compiles"
        "isderivedfrom"    "issourceof"
        "isreviewedby"     "reviews"
        "isdescribedby"    "describes"
        "isidenticalto"    "isvariantformof"

    Note:
        Only ``id`` needs to be passed on the REST API; Zenodo fills in
        ``title`` automatically.  See the full list at:
        https://github.com/inveniosoftware/invenio-rdm-records/blob/master/
        invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml
    """

    id: str


class RelatedIdentifier(BaseModel):
    """Identifier of a related resource (citations, related works).

    Used to link a dataset to papers, other datasets, software, etc.

    Attributes:
        identifier: The identifier value (e.g., DOI, URL).
        scheme: The identifier scheme, lowercase (e.g., 'doi', 'url', 'arxiv').
        relation_type: Relationship to this record as a vocabulary object
            ``{"id": "<vocab_id>"}``.  The ``id`` must be all lowercase with
            no separators (e.g., ``"cites"``, ``"issupplementedby"``).
        resource_type: Optional type of the related resource.

    Example::

        RelatedIdentifier(
            identifier="10.1038/s41597-024-03940-2",
            scheme="doi",
            relation_type=RelationType(id="cites"),
            resource_type=ResourceType(id="publication-article"),
        )
    """

    identifier: str
    scheme: str
    relation_type: RelationType
    resource_type: Optional[ResourceType] = None


class Reference(BaseModel):
    """A bibliographic reference string.

    InvenioRDM requires references to be objects with a ``reference`` key,
    not plain strings.

    Attributes:
        reference: The full citation string.
        scheme: Optional identifier scheme (e.g., 'doi', 'url').
        identifier: Optional resolved identifier for the reference.

    Example::

        Reference(reference="Wheeler et al. (1935). Observations on the "
                             "Behavior of Animals during the Total Solar "
                             "Eclipse of August 31, 1932.")
    """

    reference: str
    scheme: Optional[str] = None
    identifier: Optional[str] = None


class Community(BaseModel):
    """A Zenodo community associated with a record.

    Attributes:
        id: Community identifier (UUID or slug).
    """

    id: str


class Metadata(BaseModel):
    """Draft record metadata for InvenioRDM/Zenodo.

    This is the top-level metadata model that assembles all components
    into a valid Zenodo record metadata payload.

    Fields follow the InvenioRDM metadata reference:
        https://inveniordm.docs.cern.ch/reference/metadata/
    """

    resource_type: ResourceType
    title: str
    creators: List[Creator]
    publication_date: str
    rights: Optional[List[License]] = None
    description: Optional[str] = None
    contributors: Optional[List[Contributor]] = None
    languages: Optional[List[Language]] = None
    dates: Optional[List[Date]] = None
    version: Optional[str] = None
    publisher: Optional[str] = None
    funding: Optional[List[Funding]] = None
    subjects: Optional[List[Subject]] = None
    communities: Optional[List[Community]] = None
    related_identifiers: Optional[List[RelatedIdentifier]] = None
    references: Optional[List[Reference]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert the model to a JSON-compatible dictionary.

        Returns:
            Dictionary with None values excluded, ready for the Zenodo REST API.
        """
        return self.model_dump(exclude_none=True)

    def to_json(self) -> str:
        """Convert the model to a JSON string.

        Returns:
            JSON string with None values excluded.
        """
        return self.model_dump_json(exclude_none=True)
